"""auto update

Revision ID: 976219f5216b
Revises: 
Create Date: 2026-02-10 15:42:37.339757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976219f5216b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=False),
    sa.Column('carbon_footprint', sa.Float(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('energy_consumed', sa.Float(), nullable=True),
    sa.Column('trees_contribution', sa.Float(), nullable=True),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_metrics_id'), 'carbon_metrics', ['id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('completed_sessions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_table('tree_plantations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trees_planted', sa.Integer(), nullable=False),
    sa.Column('carbon_offset', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('tree_species', sa.String(), nullable=True),
    sa.Column('plantation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_plantations_id'), 'tree_plantations', ['id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_learning_time', sa.Integer(), nullable=True),
    sa.Column('total_carbon_footprint', sa.Float(), nullable=True),
    sa.Column('total_trees_planted', sa.Integer(), nullable=True),
    sa.Column('total_carbon_offset', sa.Float(), nullable=True),
    sa.Column('paths_completed', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_id'), 'user_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_tree_plantations_id'), table_name='tree_plantations')
    op.drop_table('tree_plantations')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_carbon_metrics_id'), table_name='carbon_metrics')
    op.drop_table('carbon_metrics')
    # ### end Alembic commands ###